### ISSUE TITLE
How to use with 'import' ES6  modules ?

### ISSUE THREAD

**Issue by AlonsoK28** [Mobius1/MiniBar#10]
I´ve tried to import the library using **webpack 4** like this:

```
import 'minibarjs/dist/minibar.min.js';
import 'minibarjs/dist/minibar.min.css';

new MiniBar('#my-item');
```

But causes this error into browser console

```
Uncaught (in promise) ReferenceError: MiniBar is not defined
```

`import` reference https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Sentencias/import

**Comment by shibnev** [comment]
?

**Comment by AlonsoK28** [comment]
> ?

https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Statements/import

**Comment by schrittweiter** [comment]
Had the same issue, try import like this

```js
import {MiniBar} from 'minibarjs';
```
