### ISSUE TITLE
Possible to scroll by clicking on the track?

### ISSUE THREAD

**Issue by stefl0n** [Mobius1/MiniBar#5]
I wonder if it is possible (with the current release?) or possibly as a future feature to scroll simply by clicking on the track. Just as it works on a system default scrollbar... 

In the progress-bar demo it is possible to scroll by clicking the track though.

![minibar](https://user-images.githubusercontent.com/8546545/67213624-9bb46d80-f41e-11e9-838d-470f1b6f23a4.gif)

**Comment by Mobius1** [comment]
This is now implemented and will be part of the next release 👍

**Comment by stefl0n** [comment]
Great, thank you  :-)

But... unfortunately it works currently with the vertical track only. See:

![minibar-v](https://user-images.githubusercontent.com/8546545/67269546-352f5e00-f4b7-11e9-8182-af86e2f12974.gif)

**Comment by Mobius1** [comment]
Fixed in [`0.4.2`](https://github.com/Mobius1/MiniBar/releases/tag/0.4.2)
